In [1]:
from anemoi.datasets import open_dataset
import xarray as xr

In [13]:
# file = '/lustre/storeB/users/nilsmk/Forcing/nordic4km_stress/n3e5_remake/zarr/nordic4_surge_atmos_1981.zarr'
# fileatm = '/lustre/storeB/users/nilsmk/anemoi-datasets/input/singleyears/nordic4_surge_atmos_1978.zarr'
fileatm = '/lustre/storeB/users/nilsmk/anemoi-datasets/input/nordic4_surge_atmos_1980-2022.zarr'
fileocn = '/lustre/storeB/users/nilsmk/anemoi-datasets/input/nordic4_surge_ocean_1980-2022.zarr'

In [14]:
# Read using anemoi:
dsocn = open_dataset(fileocn)
dsatm = open_dataset(fileatm)

# Read using xarray:
# dsatm = xr.open_zarr(fileatm)
# dsocn = xr.open_zarr(fileocn)

Dataset /lustre/storeB/users/nilsmk/anemoi-datasets/input/nordic4_surge_atmos_1980-2022.zarr has missing dates


In [15]:
dsatm.latitudes

array([46.51679993, 46.54484177, 46.57287979, ..., 87.55731964,
       87.54305267, 87.52825928])

In [16]:
dsocn.latitudes

array([46.51679993, 46.54484177, 46.57287979, ..., 87.55731964,
       87.54305267, 87.52825928])

In [7]:
lat_ocn.values

NameError: name 'lat_ocn' is not defined

In [17]:
dsatm.latitudes.values

array([46.51679924, 46.54483951, 46.57287708, ..., 87.55648231,
       87.54229933, 87.52759629])

In [15]:
# Read latitude from ocean dataset and replace in atmosphere dataset
import numpy as np
lat_ocn = dsocn.latitudes
dsatm.latitudes = lat_ocn.values
print('Replaced latitude in dsatm with latitude from dsocn')

AttributeError: cannot set attribute 'latitudes' on a 'Dataset' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.

In [10]:
print(dsatm.variables)
print(dsocn.variables)

['air_pressure_at_sea_level', 'cos_julian_day', 'cos_latitude', 'cos_local_time', 'cos_longitude', 'insolation', 'sin_julian_day', 'sin_latitude', 'sin_local_time', 'sin_longitude', 'x_wind_10m', 'y_wind_10m']
['f', 'h', 'mask_rho', 'zeta']


In [12]:
dsatm.latitudes, dsatm.longitudes

(array([46.51679924, 46.54483951, 46.57287708, ..., 87.55648231,
        87.54229933, 87.52759629]),
 array([ 0.58990593,  0.61597491,  0.64208102, ..., 79.16271461,
        80.00125385, 80.82999245]))

In [13]:
dsocn.latitudes, dsocn.longitudes

(array([46.51679993, 46.54484177, 46.57287979, ..., 87.55731964,
        87.54305267, 87.52825928]),
 array([ 0.58990979,  0.61598063,  0.64209241, ..., 79.29735565,
        80.13549042, 80.96377563]))